// Shows ChatGPT analysis summary in natural language from data in AnalysisCard.jsx
import React from 'react';

const AICard = ({ title, content }) => {
    return (
        <div className="bg-white shadow-md rounded-lg p-6 max-w-sm w-full">

            {/* AI Analysis Title and Content */}
            <h2 className="text-xl font-semibold mb-4">{title}</h2>

            {/* AI Analysis Content */}
            <p className="text-gray-700">{content}</p>
        </div>
    );
}
export default AICard;


// Note: The content prop should ideally be generated by an AI service like 
// OpenAI's GPT-4 based on the analysis data provided in AnalysisCard.jsx.