"""Add full_name, phone_number, and confirmation to User model

Revision ID: bd88d7d9b65b
Revises: 4f6aa8459f37
Create Date: 2025-10-25 11:38:22.840055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd88d7d9b65b'
down_revision = '4f6aa8459f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('confirmation_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('is_confirmed')
        batch_op.drop_column('confirmation_code')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
